Detail page redesigned with grid CSS
wolox-training/sr-angular pull request #15
Opened 2020-11-09 17:17 UTC by seromarin

## Summary
- Completed redesign the detail page with grid CSS

## Screenshot
**Desktop**
![Captura de Pantalla 2020-11-09 a la(s) 12 12 08 p  m](https://user-images.githubusercontent.com/9323975/98573945-565f1a00-2285-11eb-9c8f-e603d5d94746.png)
**Mobile**
![Captura de Pantalla 2020-11-09 a la(s) 12 11 53 p  m](https://user-images.githubusercontent.com/9323975/98573955-5828dd80-2285-11eb-8a41-bb89b84784b2.png)

## Trello Card
https://trello.com/c/pt9mL9Tv/12-redise%C3%B1o-de-la-p%C3%A1gina

2020-11-09 21:33 UTC, mcallegari10 approved these changes

2020-11-11 00:43 UTC, idcuadrowolox requested changes

2020-11-11 00:43 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +      margin: 15px auto 10px auto;
```suggestion
      margin: 15px auto 10px;
```

2020-11-11 00:43 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +    margin: 0 auto 25px auto;
```suggestion
    margin: 0 auto 25px;
```

2020-11-11 00:43 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +  grid-template-areas:
sort by name

2020-11-11 00:43 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +    grid-template-areas:
sort by name

2020-11-11 00:43 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +    margin: 10px auto 0 auto;
```suggestion
    margin: 10px auto 0;
```

2020-11-11 00:43 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +      margin: 10px auto 25px auto;
```suggestion
      margin: 10px auto 25px;
```

2020-11-11 13:33 UTC, seromarin reviewed
Fixed all comments

2020-11-11 13:33 UTC, seromarin commented on maquetacion/src/scss/_detail.scss
> +  grid-template-areas:
Sorted

2020-11-11 13:33 UTC, seromarin commented on maquetacion/src/scss/_detail.scss
> +    grid-template-areas:
Sorted

2020-11-11 14:43 UTC, idcuadrowolox approved these changes

2020-11-11 15:49 UTC, merged