Book list
wolox-training/sr-angular pull request #6
Opened 2020-10-30 22:02 UTC by seromarin

## Summary
- Completed the book list

## Screenshot
![Captura de Pantalla 2020-10-30 a la(s) 4 57 01 p  m](https://user-images.githubusercontent.com/9323975/97760593-7e09f180-1ad1-11eb-8831-11578544a462.png)

## Trello Card
https://trello.com/c/8akclPNT/30-listado-de-libros

2020-11-04 16:40 UTC, idcuadrowolox requested changes

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/index.html
> +
Please remove empty line

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/index.html
> +
same

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/index.html
> +
same

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/index.html
> +
Please remove all empty lines

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/src/scss/_styles.scss
> +  // height: 100%; Enable later
remove comment

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/src/scss/_book-list.scss
> +    width: 109px;
```suggestion
    width: 100%;
```

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/src/scss/_book-list.scss
> +    width: 109px;
It's not necessary

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +  color: $grey-light;
Sort properties by name

2020-11-04 16:40 UTC, idcuadrowolox commented on maquetacion/src/scss/_detail.scss
> +    width: 98px;
Remove this

2020-11-05 17:36 UTC, seromarin reviewed
All fixes are applied

2020-11-05 17:36 UTC, seromarin commented on maquetacion/src/scss/_detail.scss
> +    width: 98px;
Removed

2020-11-05 17:36 UTC, seromarin commented on maquetacion/src/scss/_detail.scss
> +  color: $grey-light;
Sorted in next commit

2020-11-05 17:53 UTC, idcuadrowolox approved these changes

2020-11-05 17:54 UTC, merged