Login
wolox-training/sr-angular pull request #9
Opened 2020-11-03 19:51 UTC by seromarin

## Summary
- Login completed with routing

## Screenshot
![Captura de Pantalla 2020-11-03 a la(s) 2 47 38 p  m](https://user-images.githubusercontent.com/9323975/98033473-89b42b80-1de3-11eb-9142-b43e0983622d.png)

## Trello Card
https://trello.com/c/ug8AXCwZ/32-login

2020-11-04 17:41 UTC, idcuadrowolox requested changes

2020-11-04 17:41 UTC, idcuadrowolox commented on maquetacion/src/scss/_mixins.scss
> +@mixin button($color, $bgc, $hover-color, $hover-bgc, $border-color: rgba(0,0,0,0),) {
remove last comma

2020-11-05 17:45 UTC, mcallegari10 requested changes

2020-11-05 17:45 UTC, mcallegari10 commented on maquetacion/book-detail.html
> +      <div class="back-button">
I think this `div` is not needed. If you need the styles, applied it to the `a` tag 😄

2020-11-05 17:45 UTC, mcallegari10 commented on maquetacion/src/scss/_navbar.scss
> +  &__content {
I think this is not needed, you can use the flexbox attributes in the `.nav` class

2020-11-05 17:45 UTC, mcallegari10 commented on maquetacion/src/scss/_navbar.scss
> +    width: 212.42px;
Check the previous PR #8

2020-11-05 17:45 UTC, mcallegari10 commented on maquetacion/book-list.html
> +      <div class="container">
Check the CSS, I think this is not needed

2020-11-05 17:45 UTC, mcallegari10 commented on maquetacion/book-detail.html
> +      <div class="container">
Check CSS comment, this is not needed

2020-11-05 22:29 UTC, closed without merging